on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      
      - run: echo "${{ secrets.MY_SECRET }}"


      - run: |
          import os
          print(len(os.getenv('MY_VAR')))
        shell: python
        env:
          MY_VAR: ${{ secrets.MY_SECRET }}